<a href="https://colab.research.google.com/github/Tanvisharma31/CS-704_Deep-Reinforcement_Learning_Lab/blob/m/NumPy_Basics_For_Deep_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy** Basics For Deep Learning

Remove the "#" for installing NumPy

In [36]:
#!pip install numpy

Basic array creation

Q.1 Create a 1D array with the elements [1, 2, 3, 4, 5].

In [37]:
import numpy as np
#create a 1d array
array_1d = np.array([1,2,3,4,5])
print("1D Array:",array_1d)

1D Array: [1 2 3 4 5]


Q.2 Create a 2D array with the elements [[1, 2, 3], [4, 5, 6]].

In [38]:
#create a 2d array
array_2d = np.array([[1,2,3],[4,5,6]])
print("2D Array:\n",array_2d)

2D Array:
 [[1 2 3]
 [4 5 6]]


Q.3 Create a 3x3 array filled with zeros.

In [39]:
#create an array with zeros
zeros_array=np.zeros((3,3))
print("Zeros Array:\n",zeros_array)

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q.4 Create a 2x2 array filled with ones.

In [40]:
#create an array with ones
ones_array=np.ones((3,3))
print("Ones Array:\n",ones_array)

Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Array Operations

Q.1 Create two arrays: a = [1, 2, 3] and b = [4, 5, 6].

In [41]:
#create two arrays
a=np.array([1,2,3])
b=np.array([4,5,6])


Q.2 Perform element-wise addition, subtraction, multiplication, and division on these arrays.

In [42]:
#addition
sum_array=np.add(a,b)
print("Sum:",sum_array)

Sum: [5 7 9]


In [43]:
#subtraction
diff_array=np.subtract(a,b)
print("Difference:",diff_array)

Difference: [-3 -3 -3]


In [44]:
#Multiplication
prod_array=np.multiply(a,b)
print("Multiply:",prod_array)


Multiply: [ 4 10 18]


In [45]:
#division
quotient_array=np.divide(a,b)
print("Quotient:",quotient_array)

Quotient: [0.25 0.4  0.5 ]


Matrix Multiplication

Q.1 Create two matrices: matrix_a = [[1, 2], [3, 4]] and matrix_b = [[5, 6], [7, 8]].

In [46]:
#create 2 matrix
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])


Q.2 Perform matrix multiplication on these matrices.

In [47]:
#matrix Multiplication
matrix_product=np.dot(a,b)
print("Matrix Product:\n",matrix_product)

Matrix Product:
 [[19 22]
 [43 50]]


Broadcasting

Q.1 Create an array: array = [1, 2, 3].

In [48]:
#create an array & a scalar
array=np.array([1,2,3])
scalar=2

Q.2 Multiply this array by a scalar value, e.g., 2, using broadcasting.

In [49]:
#broadcasting
broadcasted_array=array*scalar
print("Broadcasted Array:",broadcasted_array)

Broadcasted Array: [2 4 6]


Statistical Operations

Q.1 Create an array: data = [1, 2, 3, 4, 5].

In [50]:
#create an array
data=np.array([1,2,3,4,5])

Q.2 Calculate the mean, standard deviation, and sum of this array.

In [51]:
#mean
mean=np.mean(data)
print("Mean:",mean)

Mean: 3.0


In [52]:
#standard deviation
std=np.std(data)
print("Standard Deviation:",std)

Standard Deviation: 1.4142135623730951


In [53]:
#sum
sum=np.sum(data)
print("Sum:",sum)

Sum: 15


Reshaping Arrays

Q.1 Create a 1D array: array = [1, 2, 3, 4, 5, 6].

In [54]:
#create a 1d array
array=np.array([1,2,3,4,5,6])

Q.2 Reshape this array to a 2x3 array.

In [55]:
#reshaping to 2x3
reshaped=array.reshape(2,3)
print("Reshaped Array:\n",reshaped)

Reshaped Array:
 [[1 2 3]
 [4 5 6]]


Q.3 Reshape the same array to a 3x2 array.

In [56]:
#reshaping to 3x2
reshaped_array=array.reshape(3,2)
print("Reshaped Array:\n",reshaped_array)

Reshaped Array:
 [[1 2]
 [3 4]
 [5 6]]


Element-wise Operations

Q.1 Create two arrays: array_a = [1, 2, 3] and array_b = [4, 5, 6].

In [57]:
#create Array
array_a=np.array([1,2,3])
array_b=np.array([4,5,6])

Q.2 Perform element-wise addition and multiplication on these arrays.

In [58]:
#Element-wise addition
add_result=array_a + array_b
print("Element-wise Addition:",add_result)

Element-wise Addition: [5 7 9]


In [59]:
#Element-wise Multiplication
multiply_result=array_a*array_b
print("Element-wise:",multiply_result)

Element-wise: [ 4 10 18]


Slicing & indexing

Q.1 Create a 2D array: array_2d = [[1, 2, 3], [4, 5, 6], [7, 8, 9]].

In [69]:
#create 2D array
array_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("array_2d:\n", array_2d)

array_2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


Q.2 Access the element at row 1, column 1.

In [61]:
#accessing an element
element=array_2d[1,1]
print("Element at [1,1]:",element)

Element at [1,1]: 5


Q.3 Access row 1.

In [62]:
#accessing a row
row=array_2d[1,:]
print("Row:",row)

Row: [4 5 6]


Q.4 Access column 1.

In [63]:
#accessing a column
column=array_2d[:,1]
print("Column:",column)

Column: [2 5 8]


Creating Random Arrays

Q.1 Create a 3x3 array with random floats.

In [64]:
# Create a random array
random_array = np.random.rand(3, 3)
print("Random Array:\n", random_array)

Random Array:
 [[0.10630836 0.54534622 0.34157964]
 [0.49837601 0.60742334 0.3288937 ]
 [0.21665839 0.76879382 0.91433004]]


Q.2 Create a 3x3 array with random integers between 0 and 10.

In [65]:
# Create a random integer array
random_int_array = np.random.randint(0, 10, (3, 3))
print("Random Integer Array:\n", random_int_array)

Random Integer Array:
 [[9 2 9]
 [3 6 1]
 [1 7 9]]


Stacking and Concatenating Arrays

Q.1 Create two arrays: array_a = [1, 2, 3] and array_b = [4, 5, 6].

In [66]:
#create two array
array_a=np.array([1,2,3])
array_b=np.array((4,5,6))

Q.2 Perform vertical stacking on these arrays.

In [67]:
# Vertical stack
v_stack = np.vstack((array_a, array_b))
print("Vertical Stack:\n", v_stack)

Vertical Stack:
 [[1 2 3]
 [4 5 6]]


Q.3 Perform horizontal stacking on these arrays.

In [68]:
# Horizontal stack
h_stack = np.hstack((array_a,array_b))
print("Horizontal Stack:", h_stack)

Horizontal Stack: [1 2 3 4 5 6]
