# Numpy Practise Assignment

Prerequisites:

In [2]:
#!pip install numpy
import numpy as np

**Basic Array Creation**

Q.1 Create an array with 10 equally spaced numbers between 0 and 1.

In [71]:
# Create an array with 10 equally spaced numbers between 0 and 1
array = np.linspace(0, 1, 10)
print("Array:\n",array)

Array:
 [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


Q.2 Create a 1D array of 20 random integers between 1 and 100.

In [72]:
# Create a 1D array of 20 random integers between 1 and 100
random_array = np.random.randint(1, 101, size=20)
print("Random Array:\n",random_array)

Random Array:
 [52 81 19  5 31 98 56 59 81 84 93 84 42 81 37 76 91 56 24 52]


Q.3 Create a 2D array with the shape (4, 4) filled with the value 7.

In [73]:
array_2d = np.full((4, 4), 7)
print("2D Array:\n",array_2d)

2D Array:
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


Q.4 Create a 1D array of 10 elements with the same value, 3.14.

In [74]:
# Create a 1D array of 10 elements with the same value, 3.14
array_1d = np.full(10, 3.14)
print("1D Array:\n",array_1d)

1D Array:
 [3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]


Q.5 Create a 2D array with the shape (3, 3) with values ranging from 1 to 9.

In [75]:
# Create a 2D array with the shape (3, 3) with values ranging from 1 to 9
array_2d_range = np.arange(1, 10).reshape((3, 3))
print("2D Array:\n",array_2d_range)

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


**Array Operations**

Q.1 Create two arrays: a = [1, 3, 5, 7, 9] and b = [2, 4, 6, 8, 10]. Perform element-wise
subtraction.

In [76]:
# Create the arrays
a = np.array([1, 3, 5, 7, 9])
b = np.array([2, 4, 6, 8, 10])

# Perform element-wise subtraction
result_subtraction = a - b
print("Subtraction:\n",result_subtraction)

Subtraction:
 [-1 -1 -1 -1 -1]


Q.2 Multiply array a by 3: a = [2, 4, 6, 8].

In [77]:
# Create the array
a = np.array([2, 4, 6, 8])

# Multiply array a by 3
result_multiplication = a * 3
print("Multiplication:\n",result_multiplication)

Multiplication:
 [ 6 12 18 24]


Q.3 Divide array a by 2: a = [10, 20, 30, 40].

In [78]:
# Create the array
a = np.array([10, 20, 30, 40])

# Divide array a by 2
result_division = a / 2
print("Division:\n",result_division)

Division:
 [ 5. 10. 15. 20.]


Q.4 Find the element-wise modulus of two arrays: a = [5, 10, 15], b = [2, 3, 4].

In [79]:
# Create the arrays
a = np.array([5, 10, 15])
b = np.array([2, 3, 4])

# Find the element-wise modulus
result_modulus = a % b
print("Modulus:\n",result_modulus)

Modulus:
 [1 1 3]


Q.5 Create two arrays: a = [1, 2, 3], b = [4, 5, 6]. Compute the dot product.

In [80]:
# Create the arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Compute the dot product
result_dot_product = np.dot(a, b)
print("Dot Product:\n",result_dot_product)

Dot Product:
 32


**Matrix Multiplication**

Q.1 Create two matrices: a = [[2, 3], [4, 5]] and b = [[1, 0], [0, 1]]. Perform matrix
multiplication.

In [81]:
# Create the matrices
a = np.array([[2, 3], [4, 5]])
b = np.array([[1, 0], [0, 1]])

# Perform matrix multiplication
result_matrix_multiplication = np.dot(a, b)
print("Matrix Multiplication:\n",result_matrix_multiplication)

Matrix Multiplication:
 [[2 3]
 [4 5]]


Q.2 Multiply a 3x3 matrix with a 3x1 vector.

In [82]:
# Create the 3x3 matrix and 3x1 vector
matrix_3x3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
vector_3x1 = np.array([[1], [2], [3]])

# Perform matrix multiplication
result_multiplication = np.dot(matrix_3x3, vector_3x1)
print("Matrix & Vector Multiplication:\n",result_multiplication)

Matrix & Vector Multiplication:
 [[14]
 [32]
 [50]]


Q.3 Create a 4x4 identity matrix and multiply it by a 4x4 matrix filled with random
integers.

In [83]:
# Create the 4x4 identity matrix and the 4x4 matrix with random integers
identity_matrix = np.eye(4)
random_matrix = np.random.randint(1, 10, size=(4, 4))

# Perform matrix multiplication
result_identity_multiplication = np.dot(identity_matrix, random_matrix)
print("Identity Multiplication:\n",result_identity_multiplication)

Identity Multiplication:
 [[2. 1. 6. 3.]
 [7. 7. 7. 6.]
 [1. 6. 1. 6.]
 [6. 3. 6. 8.]]


Q.4 Perform matrix multiplication on two 3x3 matrices: a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
and b = [[9, 8, 7], [6, 5, 4], [3, 2, 1]].

In [84]:
# Create the matrices
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Perform matrix multiplication
result_matrix_multiplication_3x3 = np.dot(a, b)
print("3x3 Matrix Multiplication:\n",result_matrix_multiplication_3x3)

3x3 Matrix Multiplication:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


Q.5 Create a 2x3 matrix and a 3x2 matrix. Perform matrix multiplication.

In [85]:
# Create the matrices
matrix_2x3 = np.array([[1, 2, 3], [4, 5, 6]])
matrix_3x2 = np.array([[7, 8], [9, 10], [11, 12]])

# Perform matrix multiplication
result_matrix_multiplication_2x3_3x2 = np.dot(matrix_2x3, matrix_3x2)
print("2x3 matrix & 3x2 matrix Multiplication:\n",result_matrix_multiplication_2x3_3x2)

2x3 matrix & 3x2 matrix Multiplication:
 [[ 58  64]
 [139 154]]


**Broadcasting**

Q.1 Create a 1D array: array = [10, 20, 30]. Subtract a scalar value, 5, using broadcasting.

In [86]:
# Create a 1D array
array = np.array([10, 20, 30])
scalar_value=5

# Subtract the scalar value 5 from each element in the array using broadcasting
result = array - scalar_value

print("Original array:", array)
print("Resulting array after subtracting 5:", result)

Original array: [10 20 30]
Resulting array after subtracting 5: [ 5 15 25]


Q.2 Create a 3x3 array and a 3x1 array. Add them using broadcasting.

In [87]:
# Create a 3x3 array
array_3x3 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
# Create a 3x1 array
array_3x1 = np.array([[1],[2],[3]])
# Add the arrays using broadcasting
result = array_3x3 + array_3x1
print("\nResult of Broadcasting Addition:\n",result)



Result of Broadcasting Addition:
 [[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


Q.3 Divide a 4x4 array by a scalar value, 2, using broadcasting.

In [88]:
#Create 4x4 array
array_3x3 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9],[1, 4, 7]])
Scalar_value=2
#Divide the array by the scalar value
result=array_3x3/Scalar_value
print("\nResult of Broadcalting Dividing:\n",result)



Result of Broadcalting Dividing:
 [[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]
 [0.5 2.  3.5]]


Q.4 Create a 3x3 array and add 3 to each element using broadcasting.

In [89]:
# Create a 3x3 array
array_3x3 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
#add 3 value
result=array_3x3+3
print("\nResult of Broadcasting addition:\n",result)



Result of Broadcasting addition:
 [[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Q.5 Multiply a 1D array of shape (5,) by a 2D array of shape (5, 5) using broadcasting.

In [90]:
# create the 1D array
array_1d = np.array([1, 2, 3, 4, 5])

# Define the 2D array
array_2d = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])

# Multiply using broadcasting
result = array_2d * array_1d[:, np.newaxis]

print("Result of multiplication:\n",result)
print(result)

Result of multiplication:
 [[  1   2   3   4   5]
 [ 12  14  16  18  20]
 [ 33  36  39  42  45]
 [ 64  68  72  76  80]
 [105 110 115 120 125]]
[[  1   2   3   4   5]
 [ 12  14  16  18  20]
 [ 33  36  39  42  45]
 [ 64  68  72  76  80]
 [105 110 115 120 125]]


**Statistical Operations**

Q.1 Calculate the median of the array: data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10].

In [91]:
# Define the data array
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Calculate the median of the array
median = np.median(data)
print("Median:", median)

Median: 5.5


Q.2 Calculate the mode of the array: data = [1, 2, 2, 3, 4, 4, 4, 5, 6].

In [92]:
from scipy import stats
# Sample data array
data = np.array([1, 2, 2, 3, 4, 4, 4, 5, 6])

# Calculate the mode
mode_result = stats.mode(data)

# Print the mode
print( "Mode:",mode_result)

Mode: ModeResult(mode=4, count=3)


Q.3 Calculate the range of the array: data = [10, 20, 30, 40, 50].

In [93]:
data = np.array([10, 20,30,40,50])
range_of_data = np.ptp(data)
print("The range of the array is:", range_of_data)

The range of the array is: 40


Q.4 Calculate the 25th percentile of the array: data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10].

In [94]:
# Sample data array
data = np.array([1, 3, 3, 4, 5, 6, 7, 8, 9, 10])

# Calculate the 25th percentile
percentile_25 = np.percentile(data, 25)

print(" 25th percentile of the array:",percentile_25)

 25th percentile of the array: 3.25


Q.5 Calculate the correlation coefficient between two arrays: a = [1, 2, 3, 4, 5] and b = [2,
4, 6, 8, 10].

In [95]:
# Define the arrays
a = np.array([1, 2, 3, 4, 5])
b = np.array([2, 4, 6, 8, 10])

# Calculate the correlation coefficient
correlation_matrix = np.corrcoef(a, b)
correlation_coefficient = correlation_matrix[0, 1]

print("Correlation Coefficient:", correlation_coefficient)

Correlation Coefficient: 0.9999999999999999


**Reshaping Arrays**

Q.1 Reshape a 1D array of 12 elements to a 3x4 array.

In [96]:
# Create a 1D array with 12 elements
array_1d = np.arange(12)
print("Original array:")
print(array_1d)
# Reshape the array to 3x4
array_2d = array_1d.reshape(3, 4)

print("\nReshaped array to 3x4:\n",array_2d)

Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped array to 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Q.2 Reshape a 2D array of shape (6, 2) to (3, 4).

In [97]:
# Original array of shape (6, 2)
original_array = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

# Reshape to (3, 4)
reshaped_array = original_array.reshape(3, 4)

print("Original array:")
print(original_array)
print("\nReshaped array:")
print(reshaped_array)

Original array:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]

Reshaped array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Q.3 Create a 4x4 array and flatten it.

In [98]:
# Create a 4x4 array
array_4x4 = np.array([[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12],
                      [13, 14, 15, 16]])

# Flatten the array
flattened_array = array_4x4.flatten()

print("Original 4x4 array:")
print(array_4x4)
print("\nFlattened array:")
print(flattened_array)

Original 4x4 array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Flattened array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


Q.4 Reshape a 3D array of shape (2, 3, 4) to (4, 3, 2).

In [99]:
# Create an array of shape (2, 3, 4)
array = np.arange(24).reshape(2, 3, 4)

# Reshape the array to shape (4, 3, 2)
reshaped_array = array.reshape(4, 3, 2)

print("Original array shape:", array.shape)
print("Reshaped array shape:", reshaped_array.shape)
print("Reshaped array:\n", reshaped_array)

Original array shape: (2, 3, 4)
Reshaped array shape: (4, 3, 2)
Reshaped array:
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


Q.5 Reshape a 1D array to a 2D array with 1 row and many columns.

In [100]:
# Create a 1D array
array_1d = np.array([1, 2, 3, 4, 5, 6])
print("Array 1D:",array_1d)
# Reshape the 1D array to a 2D array with 1 row and many columns
array_2d = array_1d.reshape(1, -1)

print("\nReshape a 1D array:\n",array_2d)

Array 1D: [1 2 3 4 5 6]

Reshape a 1D array:
 [[1 2 3 4 5 6]]


**Element-wise Operations**

Q.1 Create two arrays: a = [1, 3, 5] and b = [2, 4, 6]. Perform element-wise division.

In [101]:
# create Arrays
a = [1, 3, 5]
b = [2, 4, 6]
# element-wise division
Division=np.divide(a,b)
print("Division:",Division)

Division: [0.5        0.75       0.83333333]


Q.2 Create two arrays: a = [2, 4, 6] and b = [1, 3, 5]. Perform element-wise modulus.

In [102]:
# create Arrays
b = [1, 3, 5]
a = [2, 4, 6]
#element-wise modulus
Modulus=np.mod(a,b)
print("Modulus:",Modulus)

Modulus: [0 1 1]


Q.3 Add 10 to each element in the array: a = [1, 2, 3, 4, 5].

In [103]:
# create array
a = [1, 2, 3, 4, 5]
#Add 10 to each element in the array
add=np.add(a,10)
print("Added 10 to each element: ",add)

Added 10 to each element:  [11 12 13 14 15]


Q.4 Subtract 5 from each element in the array: b = [10, 20, 30, 40, 50].

In [104]:
#create array
b = [10, 20, 30, 40, 50]
#Subtract 5 from each element in the array
subtract=np.subtract(b,5)
print("Subtract 5 from each element:",subtract)

Subtract 5 from each element: [ 5 15 25 35 45]


Q.5 Square each element in the array: c = [1, 2, 3, 4, 5].

In [105]:
#Create a 1D array
c = np.array([1, 2, 3, 4, 5])
#Square each element in the array
squared_c = np.square(c)
print(" Square each element:",squared_c)

 Square each element: [ 1  4  9 16 25]


**Slicing and Indexing**

Q.1 Create a 3D array: array_3d = [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]. Access
the element at [1, 1, 1].

In [106]:
# Create a 3D array
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
#Access the element at [1, 1, 1].
element_at_1=array_3d[1, 1, 1]
print("element at [1, 1, 1]:",element_at_1)

element at [1, 1, 1]: 11


Q.2 Slice the first layer of a 3D array: array_3d = [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11,
12]]].

In [107]:
# Create a 3D array
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
# Slice the first layer of a 3D array
first_layer_slice = array_3d[0]
print(" first layer of a 3D array:",first_layer_slice)


 first layer of a 3D array: [[1 2 3]
 [4 5 6]]


Q.3 Access all elements in the last row of the array: array_2d = [[10, 20, 30], [40, 50, 60],
[70, 80, 90]].

In [108]:
#Create a 2D array
array_2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
#Access all elements in the last row of the array
last_row = array_2d[-1]
print(" last row of the array:",last_row)

 last row of the array: [70 80 90]


Q.4 Access all elements in the first column of the array: array_2d = [[10, 20, 30], [40, 50,
60], [70, 80, 90]].

In [109]:
array_2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
# Access all elements in the first column of the array
last_row = array_2d[:,0]
print("all elements in the first column:\n",last_row)

all elements in the first column:
 [10 40 70]


Q.5 Slice the last two rows and columns of the array: array_2d = [[10, 20, 30], [40, 50,
60], [70, 80, 90]].

In [110]:
#Slice the last two rows and columns of the array
Last_two_rows=array_2d[-2:,-2:]
print("the last two rows and columns of the array:\n",Last_two_rows)

the last two rows and columns of the array:
 [[50 60]
 [80 90]]


**Creating Random Arrays**

Q.1 Generate a random array of 20 elements with values between 0 and 1.

In [111]:
#Generate a random array
random_array=np.random.randint(0,1,size=20)
print("a random array of 20 elements:",random_array)

a random array of 20 elements: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


Q.2 Create a 4x4 array with random integers between 10 and 20.

In [112]:
# Create a 4x4 array with random integers
random_array=np.random.randint(10,20,size=(4,4))
print("a 4x4 array with random integers :\n",random_array)

a 4x4 array with random integers :
 [[18 13 16 10]
 [12 17 19 16]
 [14 16 18 14]
 [14 19 17 18]]


Q.3 Create a 3x3 array with random floats between -1 and 1.

In [113]:
#Create a 3x3 array with random floats between -1 and 1.
random_array=np.random.uniform(-1,1,size=(3,3))
print("a 3x3 array with random floats:\n",random_array)

a 3x3 array with random floats:
 [[-0.39101162  0.6228177  -0.23457112]
 [ 0.60472798 -0.31356206  0.55321881]
 [ 0.7081545  -0.86606311  0.4972413 ]]


Q.4 Generate an array of 15 random integers between 100 and 200.

In [114]:
#Generate an array of 15 random integers between 100 and 200.
random_array=np.random.randint(100,200,size=15)
print(" an array of 15 random integers:",random_array)

 an array of 15 random integers: [128 115 160 180 179 168 131 184 121 159 147 116 186 153 136]


Q.5 Create a 5x5 array with random floats between 0 and 10.

In [115]:
#Create a 5x5 array with random floats between 0 and 10.
random_array=np.random.uniform(0,10,size=(5,5))
print("a 5x5 array with random floats:\n",random_array)

a 5x5 array with random floats:
 [[4.61754371 6.81845897 4.0556972  3.64919985 0.74611453]
 [4.06194545 7.9539775  1.68354126 7.28970715 1.12160381]
 [9.49636438 4.64671909 7.45336019 4.79249814 3.89401125]
 [2.39316967 5.04352839 5.02486493 3.36729399 4.96297182]
 [6.31110727 8.45899867 3.44237962 5.36074651 6.61031989]]


**Stacking and Concatenating Arrays**

Q.1 Vertically stack two arrays: a = [[1, 2], [3, 4]] and b = [[5, 6], [7, 8]].

In [116]:
#create 2 arrays
a = [[1, 2], [3, 4]]
b = [[5, 6], [7, 8]]
#Vertically stack two arrays:
stacked_array=np.vstack((a,b))
print("Vertically stack two arrays:\n",stacked_array)


Vertically stack two arrays:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


Q.2 Horizontally stack two arrays: a = [[1, 2], [3, 4]] and b = [[5, 6], [7, 8]].

In [117]:
#Horizontally stack two arrays
stacked_array=np.hstack((a,b))
print("Horizontally stack two arrays:\n",stacked_array)

Horizontally stack two arrays:
 [[1 2 5 6]
 [3 4 7 8]]


Q.3 Concatenate two 1D arrays: a = [1, 2, 3] and b = [4, 5, 6].

In [118]:
#create 2 1D arrays
a = [1, 2, 3]
b = [4, 5, 6]
#Concatenate two 1D arrays
Concatenated_array=np.concatenate((a,b))
print("Concatenate two 1D arrays:\n",Concatenated_array)


Concatenate two 1D arrays:
 [1 2 3 4 5 6]


Q.4 Concatenate two 3x3 arrays along rows: a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] and b = [[10,
11, 12], [13, 14, 15], [16, 17, 18]].

In [119]:
#Create 2 3x3 arrays
a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
b = [[10,11, 12], [13, 14, 15], [16, 17, 18]]
#Concatenate two 3x3 arrays along rows
Concatenated_array=np.concatenate((a,b),axis=0)
print("Concatenate two 3x3 arrays along rows:\n",Concatenated_array)


Concatenate two 3x3 arrays along rows:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


Q.5 Concatenate two 3x3 arrays along columns: a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] and b =
[[10, 11, 12], [13, 14, 15], [16, 17, 18]].

In [120]:
#Concatenate two 3x3 arrays along column
Concatenated_array=np.concatenate((a,b),axis=1)
print("Concatenate two 3x3 arrays along columns:\n",Concatenated_array)


Concatenate two 3x3 arrays along columns:
 [[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]
